kind: Deployment
apiVersion: apps/v1
metadata:
  name: osmosis-proposal-atomfeed
spec:
  replicas: 1
  selector:
    matchLabels:
      app: osmosis-proposal-atomfeed
  template:
    metadata:
      labels:
        app: osmosis-proposal-atomfeed
    spec:
      containers:
      - args:
        image: derorisan/osmosis-proposal-atomfeed
        imagePullPolicy: Always
        name: osmosis-proposal-atomfeed
        ports:
        - containerPort: 4000
          protocol: TCP
---
kind: Service
apiVersion: v1
metadata:
  name: osmosis-proposal-atomfeed
spec:
  ports:
  - name: "http-port"
    protocol: TCP
    port: 80
    targetPort: 4000
  selector:
    app: osmosis-proposal-atomfeed
---
# # ingress
# apiVersion: networking.k8s.io/v1
# kind: Ingress
# metadata:
#   name: lb
#   namespace: ip-deroris-net-prod
#   annotations:
#     nginx.ingress.kubernetes.io/rewrite-target: /
# spec:
#   rules:
#     - host: osmosis-proposal-atomfeed.deroris.net
#       http:
#         paths:
#           - path: /
#             pathType: Prefix
#             backend:
#               service:
#                 name: osmosis-proposal-atomfeed
#                 port:
#                   number: 80